# Generated by Django 4.2.2 on 2026-03-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ("date",)},
        ),
        migrations.AlterModelOptions(
            name="table",
            options={"ordering": ("name",)},
        ),
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
