# Generated by Django 4.2.2 on 2026-03-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_alter_booking_options_alter_table_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
