# Generated by Django 4.2.2 on 2026-03-06 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_alter_booking_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("table", "date")},
        ),
    ]
