# Generated by Django 4.2.2 on 2026-03-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0004_alter_booking_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_declined",
            field=models.BooleanField(default=False),
        ),
    ]
